---
- name: Create nginx directory
  file:
    path: "{{ project_path }}/nginx"
    state: directory

- name: Copy Dockerfile for NGINX
  copy:
    src: Dockerfile
    dest: "{{ project_path }}/nginx/Dockerfile"

- name: Copy NGINX configuration
  template:
    src: nginx.conf.j2
    dest: "{{ project_path }}/nginx/nginx.conf"

