---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Create project directory
  file:
    path: "{{ project_path }}"
    state: directory

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yml
    dest: "{{ project_path }}/docker-compose.yml"

- name: Start Docker Compose
  command: docker-compose up -d
  args:
    chdir: "{{ project_path }}"

