name: Deploy Dockerized Web Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Get IP from inventory
      id: get_ip
      run: |
        IP=$(grep -oP '(?<=^)[0-9.]+(?= ansible_user=qwerty)' ansible/inventory)
        echo "::set-output name=ip::$IP"

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_IP: ${{ steps.get_ip.outputs.ip }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H $REMOTE_IP >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
      run: |
        ansible-playbook -i ansible/inventory ansible/playbook.yml -v
